sonar.projectKey=danielaureliano_weather-ticker
sonar.organization=danielaureliano
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/coverage/**,**/docs/**
